// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadAndLoadMd(arg1:string):Promise<string>;

export function GetExampleMarkdown():Promise<string>;

export function GetStartupFile():Promise<string>;

export function LoadMarkdownFile(arg1:string):Promise<string>;

export function LoadRelativeMdFile(arg1:string,arg2:string):Promise<Record<string, string>>;

export function OpenExternalLink(arg1:string):Promise<void>;

export function OpenFileDialog():Promise<string>;
