// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadAndLoadMd(arg1) {
  return window['go']['main']['App']['DownloadAndLoadMd'](arg1);
}

export function GetExampleMarkdown() {
  return window['go']['main']['App']['GetExampleMarkdown']();
}

export function GetStartupFile() {
  return window['go']['main']['App']['GetStartupFile']();
}

export function LoadMarkdownFile(arg1) {
  return window['go']['main']['App']['LoadMarkdownFile'](arg1);
}

export function LoadRelativeMdFile(arg1, arg2) {
  return window['go']['main']['App']['LoadRelativeMdFile'](arg1, arg2);
}

export function OpenExternalLink(arg1) {
  return window['go']['main']['App']['OpenExternalLink'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}
